development:
  adapter: postgresql
  encoding: unicode
  database: timasbite2_development
  pool: 5
  username: timasbite2
  password: <%= ENV['DATABASE_PASSWORD'] %>
  host: <%= ENV['DATABASE_HOST'] %>

test:
  adapter: postgresql
  encoding: unicode
  database: timasbite2_test
  pool: 5
  username: timasbite2
  password: <%= ENV['DATABASE_PASSWORD'] %>
  host: <%= ENV['DATABASE_HOST'] %>
